### ISSUE TITLE
Object Not Found

### ISSUE THREAD

**Issue by manigopal** [panigrc/SimpleCiShop#38]
I'm getting 

Object not found!

The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster. 

also do add the web url where its hosted for our reference / demo.

**Comment by panigrc** [comment]
Hi @manigopal I know it's been a long time (almost a year) but thank you for the suggestions, I will try to upload a demo as soon as possible.
